### ISSUE TITLE
Can't get it to work in Sway 1.4

### ISSUE THREAD

**Issue by MRusinov** [burik666/yagostatus#2]
I'm using Sway 1.4 on Debian SID. If I'm setting "status_command exec ~/go/bin/yagostatus --config ~/.config/i3/yagostatus.yml 2> /tmp/yagostatus.log", I get "[invalid i3bar json]" in swaybar.
Contents of /tmp/yagostatus.log is only 1 line:
2020/06/09 22:29:29 main.go:124: INFO exit

**Comment by burik666** [comment]
Fixed.
Thanks a lot.

I have never test yagostatus in sway.
